config/routes.rb
Rails.application.routes.draw do

    resource :user , :controller => 'user'
    resource :company, :controller => 'company'
    resource :sessions

    root 'welcome#homepage'   

    get 'users/signup'
    get 'analyzer/centralAnalysis'
    get 'viewer/news'
    get 'viewer/company'
    get 'viewer/list'
    get 'welcome/about'

    get '/index' => 'company#index'
    get 'company/index'
    post 'company/index'

    post '/users' => 'user#create'
    get '/users' => 'user#create'

    get    '/login',   to: 'session#login'
    post   '/login',   to: 'session#create'
    get '/logout',  to: 'session#destroy'

    
    #get 'session/login'
    get 'welcome/homepage'
    
    #get 'login' => 'session#login'
    #post 'login' => 'session#login'

    get '/signup' => 'user#signup'
    
    post '/companies' => 'company#show'
    get '/companies' => 'company#show'
    #get "/views/session/login.html", to: "session#login", as: "logins"

    post "/signup", to: "user#signup"
    get "/signup", to: "user#signup"

    get "/refreshtweets", to: "analyzer#refresh_tweets", as: "refresh"
    get "/centralAnalysis/:id", to: "analyzer#centralAnalysis", as: "analysis" , :constraints => { :id => /[^\/]+/ }
    get "/homepage", to: "welcome#homepage", as: "homepage"
    get "/about", to: "welcome#about", as: "about"

    get "/views/analyzer/data/", to: "analyzer#historic_data", as: "historic" , :constraints => { :tick => /[^\/]+/ }
    post "/views/analyzer/data/", to: "analyzer#historic_data", :constraints => { :tick => /[^\/]+/ }
    
    get "/index", to: "company#index"
    get "/views/company/searchView.html", to: "company#create", :defaults => { :format => 'html' }
    get "/views/company/show.html", to: "company#show"

    get "/news", to: "viewer#news", as: "news"
    #get "/views/analyzer/centralAnalysis.html", to: "analyzer#centralAnalysis", as: "centralAnalysis"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/viewer_controller.rb
class ViewerController < ApplicationController

  def list
  	if params[:search]
		   @company = Company.search(params[:search])
		else
		   @company = Company.all
		   @company = Company.paginate(:page => params[:page], :per_page => 30)
		end
  end
   def news
   	@bloom= BloombergStream.all.reverse
   end
end

app/views/viewer/company.html.erb
<link rel="stylesheet" href="/assets/css/session.scss">
<link rel="stylesheet" href="/assets/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="/assets/css/bootstrap.min.css">
<head> <div><nav class="navbar navbar-inverse navbar-fixed-top">
        <a class="navbar-brand" href="#">Investment Aid System</a>
        <ul class="nav navbar-nav">
            <li ><a href="/views/welcome/homepage.html">Home</a></li>
            <li class="active"><a href="/views/applicaton/company.html">Companies</a></li>
            <li><a href="/views/viewer/news.html">News</a></li>
            <li ><a href="/views/welcome/about.html">About</a></li>
            <li><a href="/views/session/login.html">Login</a></li>
          </ul>

        </nav>
    </div>
</head>
<br>
<br>
<h1>Viewer#company</h1>
<p>Find me in app/views/viewer/company.html.erb</p>
<a href="/views/analyzer/centralAnalysis.html">Analysis page</a>

app/views/viewer/list.html.erb
<link rel="stylesheet" href="/assets/css/session.scss">
<link rel="stylesheet" href="/assets/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="/assets/css/bootstrap.min.css">
<head> 
   <%= render 'shared/navbar_Layout' %>
</head>
<br>
<br>
<h1 align="center" style="color:white">Company List</h1>
<p style="color:white;font-size:110%" align="center">This list consist of companies listed in the NASDAQ and NYSE Exchange</p>
<br>
<div class ="row">
    <div class ="col-md-1"></div>
    <div class ="col-md-6" align="right">
        <%= form_tag(companies_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Company" %>
        <%= submit_tag "Search" %>
        <% end %>
    </div>
        
    <div class ="col-md-5" align="left"><text bgcolor="#000000" style="color:white;font-size:120%"> <%= will_paginate @comp %> </text></div>
</div>

<% if @company.blank? %>
  <h4>There are no company containing the term <%= params[:search] %>.</h4>
<% end %>

<%= will_paginate @company %>
<iv class ="col-md-4"></div>
<div class ="col-md-12">
    <div class ="col-md-2"></div>
    <div class ="col-md-10">
            <table class ="table table-bordered"  bgcolor="#fbfbfb" style="width: 80%; marginLeft:30px;">
            <thead class="">                       
              <tr bgcolor="#000000" style="height: 50px;color:white;">   
                <th>No. </th>                    
                <th>Company Name</th>
                <th> Company Tickers </th> 
                <th> Exchange  </th> 
              </tr>
            </thead>
                <% @company.each do |company|  %> 
              <tr bgcolor="#fbfbfb">
                <td><%= company.id %></td>
                <td><%= company.company_name %></td>
                <td><a href="/centralAnalysis/<%= company.stock_tickers%>"> <%= company.stock_tickers%></a></td>
                <td><%= company.exchange %></td>
              </tr>
            <% end %>                  
            </table>  
    </div>
</div>
      
</body>

app/views/viewer/news.html.erb
<link rel="stylesheet" href="/assets/css/session.scss">
<link rel="stylesheet" href="/assets/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="/assets/css/bootstrap.min.css">
<head><%= render 'shared/navbar_Layout' %>
   <style type="text/css">
        .bgwrapper {
           width:100%;
           height:100%;
           background-size:cover;
           background-attachment:fixed;    
        }
    </style>
</head>
<br>
<br>
  <h1 align="center" style="color:white">News</h1>
    <p style="color:white;font-size:110%" align="center">All news are pulled from Bloombergnews.com</p>
<body class="bgwrapper" background="/assets/background.png"  style="position:static;overflow:auto;background-repeat:no-repeat;background-size:cover;">
     <% if @bloom != " " %>
       <% @bloom.each_slice(3) do |blooms| %>
        <% blooms.each do |s| %>
          <div class="thumbnail col-md-8" style="width:800px;left:20%">
            <div class="caption">
              <h3><%= s.headlines %> </h3><h5><%= s.newsDate %></h5>
              <p><%= s.story %></p>
              <p>Polarity : <%= s.polarity %></p><p>Subjectivity : <%= s.subjectivity %></p>
              <p><a href=<%= s.newsUrl %> class="btn btn-logins" role="button" style="color:white;">Read More</a></p> 
            </div> 
          </div>
        <% end %><% end %><% end %> 
</body>  
        
 